server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jwt_security
    username: admin
    password: 6e96c406d6008575611293c6388a713
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    #dropa as tabelas ao parar a execucao
    #hibernate:
      #ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
    show-sql: true
